require("blumaa.remap")
require("blumaa.cat")
-- require("blumaa.copilot")
require("blumaa.gitsigns")
require("blumaa.harpoon")
require("blumaa.indent-blankline")
require("blumaa.lsp")
require("blumaa.nvim-tree")
require("blumaa.neotest")
require("blumaa.packer")
require("blumaa.rust-tools")
require("blumaa.set")
require("blumaa.telescope")
require("blumaa.treesitter")
